node {
	stage('SCM checkout'){
		git checkout 
	}
	
	stage('SCM checkout'){
	def mvnhome  = tool name: 'maven3', type: 'maven'
		  clean install -DskipTests 
		  "${mvnhome}/bin/mvn  package"
	}
}